import { useParams, Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Copy, Download, ArrowLeft, CheckCircle2 } from 'lucide-react';
import { useState } from 'react';

export default function DocsViewer() {
  const { id } = useParams();
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="max-w-4xl mx-auto bg-[var(--bg-surface)] border border-[var(--border-color)] rounded-2xl shadow-sm overflow-hidden"
    >
      {/* Top Toolbar */}
      <div className="border-b border-[var(--border-color)] bg-[var(--bg-base)] p-4 flex items-center justify-between">
        <Link to={`/project/${id || '123'}`} className="inline-flex items-center text-sm font-medium text-[var(--text-muted)] hover:text-brand-500 transition-colors">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to Project
        </Link>
        <div className="flex gap-2">
          <button 
            onClick={handleCopy}
            className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium bg-[var(--bg-surface)] border border-[var(--border-color)] hover:border-brand-500 rounded-lg transition-all"
          >
            {copied ? <CheckCircle2 className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
            {copied ? 'Copied!' : 'Copy Markdown'}
          </button>
          <button className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium bg-brand-600 text-white hover:bg-brand-500 rounded-lg transition-all">
            <Download className="w-4 h-4" /> Export
          </button>
        </div>
      </div>

      {/* Document Content (Simulated Markdown rendering) */}
      <div className="p-8 md:p-12 prose prose-slate dark:prose-invert max-w-none">
        <h1 className="font-display text-4xl font-bold mb-4">Vehicle Rental API - README</h1>
        <p className="text-lg text-[var(--text-muted)] mb-8">Generated by Docurion AI</p>
        
        <h2 className="font-display text-2xl font-semibold mt-8 mb-4 border-b border-[var(--border-color)] pb-2">Overview</h2>
        <p className="mb-6">This project is a backend API for managing a vehicle rental service. It handles user authentication, vehicle inventory, and booking reservations.</p>
        
        <h2 className="font-display text-2xl font-semibold mt-8 mb-4 border-b border-[var(--border-color)] pb-2">Tech Stack</h2>
        <ul className="list-disc pl-5 mb-6 space-y-1">
          <li>Node.js</li>
          <li>Express.js</li>
          <li>MongoDB (Mongoose)</li>
        </ul>
        
        <div className="bg-[var(--bg-base)] border border-[var(--border-color)] rounded-lg p-4 font-mono text-sm mt-8">
          // Final AI markdown will be injected here
        </div>
      </div>
    </motion.div>
  );
}